osx_image: xcode8.3
language: objective-c
branches:
  only:
    - master
before_install:
    - gem install xcpretty
before_script:
    - set -o pipefail
script:
    - xcodebuild test -project ./Evolver.xcodeproj -scheme EvolverTests -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,id=ABBD7191-486B-462F-80B4-AE08C5820DA1' | xcpretty -c
